#!/bin/sh

# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_COMPONENT_NAME_FANCY="Command Line Interface (CLI)"
OPENBATON_COMPONENT_NAME=cli
OPENBATON_COMPONENT_RELATIVE_SUBPATH=cli

OPENBATON_BASE_DIR=/usr
OPENBATON_COMPONENT_EXE_DIR=${OPENBATON_BASE_DIR}/bin
OPENBATON_COMPONENT_EXE=${OPENBATON_BASE_DIR}/bin/openbaton

OPENBATON_BASE_CONFIG_DIR=/etc/openbaton
OPENBATON_COMPONENT_CONFIG_FILE=openbaton-${OPENBATON_COMPONENT_NAME}.properties

OPENBATON_COMPONENT_JAR_FILE_NAME=openbaton-${OPENBATON_COMPONENT_NAME}
OPENBATON_COMPONENT_JAR_INSTALL_DIR=/usr/lib/openbaton/${OPENBATON_COMPONENT_RELATIVE_SUBPATH}


####################
#### Open Baton ####
####################

set_jar_version () {
    openbaton_component_jar_file_name_versioned=$(ls -ct ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | head -n 1)
    if [ "${openbaton_component_jar_file_name_versioned}" = "" ]; then
        log_failure_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is not installed (jar-file not found)"
        exit 1
    else
        sed -i "s@_openbaton_cli_jar=.*@_openbaton_cli_jar=${OPENBATON_COMPONENT_JAR_INSTALL_DIR}/${openbaton_component_jar_file_name_versioned}@g" ${OPENBATON_COMPONENT_EXE}
    fi
}

fix_openbaton_exe () {
    #export OPENBATON_COMPONENT_EXE=${OPENBATON_COMPONENT_EXE}
    sed -i "s@source gradle.properties@#source gradle.properties@g" ${OPENBATON_COMPONENT_EXE}
}

configure () {
    log_success_msg "Configuring Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation .."
    set_jar_version
    chmod a+x ${OPENBATON_COMPONENT_EXE_DIR}/openbaton
    
    # Temporary fix TODO: do it properly
    fix_openbaton_exe

    log_success_msg "Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation completed"
    log_success_msg "To configure the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} for your Open Baton installation type the following command and provide the inputs required:"
    log_success_msg "   source ${OPENBATON_BASE_CONFIG_DIR}/${OPENBATON_COMPONENT_CONFIG_FILE}"
}

configure
